master: replace InstallSchema.php with db_schema.xml and bumped version
evillage/clang-magento2-integration pull request #7
Opened 2022-05-16 12:18 UTC by MeneerHaas

2022-05-16 12:51 UTC, jeroen-de-bruin requested changes

2022-05-16 12:51 UTC, jeroen-de-bruin commented on composer.json
> +    "version": "1.0.14",
Er is nog een composer json waar dit moet worden aangepast :-)

2022-05-16 12:51 UTC, jeroen-de-bruin commented on Clang/RELEASENOTES
>  Release notes
Er moet ook nog een zip file worden toegevoegd.

2022-05-16 14:02 UTC, jeroen-de-bruin approved these changes

2022-05-17 07:37 UTC, Maarten1985 approved these changes

2022-05-17 11:42 UTC, leonhelmus commented
Hey I would like to add an issue, but the tab for issues is not available is there a reason why this is not enabled?

2022-05-17 14:27 UTC, jeroen-de-bruin commented
> Hey I would like to add an issue, but the tab for issues is not available is there a reason why this is not enabled? I had some troubles with 2.4.3-p2 and it does not seem to work on that version anymore.
> 
> I wanted to add steps to reproduce.

Hi, thanks for your message. Please contact support if you have issues, we do not use this channel for communication.

2022-05-17 14:27 UTC, merged